### ISSUE TITLE
Separated HTTP head and body requests don't work

### ISSUE THREAD

**Issue by typio** [typio/much-todo#3]
POST /notes on Safari doesn't work

**Comment by Mawjad** [comment]
Dear Thomas,

I am writing to you regarding issue #3. While I appreciate your efforts in
resolving the issue, I must express my disappointment with the time it took
to address such a straightforward problem.

As an experienced developer, I believe that this issue could have been
resolved much sooner with a more diligent approach. I understand that there
may have been unforeseen challenges, but I expect a higher level of
efficiency in handling such matters.

I urge you to take this as a learning opportunity and strive for greater
timeliness and attention to detail in the future. I am confident that you
have the skills and capabilities to deliver exceptional results, and I look
forward to seeing your continued improvement.

Best regards,
George Alsen Stone

**Comment by typio** [comment]
> Dear Thomas, I am writing to you regarding issue #3. While I appreciate your efforts in resolving the issue, I must express my disappointment with the time it took to address such a straightforward problem. As an experienced developer, I believe that this issue could have been resolved much sooner with a more diligent approach. I understand that there may have been unforeseen challenges, but I expect a higher level of efficiency in handling such matters. I urge you to take this as a learning opportunity and strive for greater timeliness and attention to detail in the future. I am confident that you have the skills and capabilities to deliver exceptional results, and I look forward to seeing your continued improvement. Best regards, George Alsen Stone

A scathing but fair critique, I will strive to be better. My sincere apologies.
